from collections import namedtuple
from datetime import datetime

from interpreters import InterpreterFactory
from response_generators import ResponseGenerator
from action_selectors import ActionSelectorFactory
from working_memory import WorkingMemory

from person_profile import PersonProfile

import unittest 

class Chatbot(object):
	""" Agent model that simulates dialog. It is an extension of a dialog 
	manager with improved functionality such as individualism and sophisticated
	goal evaluation functions. 

	This is a base class for designing more complicated chatbots, however,
	it will return a very basic chatbot for test purposes.

	"""

	message_history = []
	_meta = {}

	def __init__(self):
		actionSelectorFactory = ActionSelectorFactory()
		interpreterFactory = InterpreterFactory()
		InterpreterClass = interpreterFactory.get_interpreter()
		ActionSelectorClass = ActionSelectorFactory().create()

		self.profile = PersonProfile()
		self.working_memory = WorkingMemory()
		self.a_s = ActionSelectorClass(self.working_memory, self.profile)
		self.interpreter = InterpreterClass(self.working_memory, self.profile)


	def log_message(self, msg, origin):
		valid_origins = ['user', 'bot']
		message_status = namedtuple('status', ['msg', 'origin', 'timestamp'])

		if origin not in valid_origins:
			raise ValueError("invalid origin")

		message = (msg, origin, datetime.now())
		self.message_history.append(message)


	def respond(self): 
		""" Response generated by chatbot. Acts as an end point
		for response communication. Allows for post-processing of the response
		message.

		"""
		msg = self._create_response()
		self.log_message(msg, 'bot')
		return msg

	def _create_response(self):
		return self.a_s.select_action()

	def recieve(self, msg):
		self.interpreter.interpret(msg)
		self.log_message(msg, 'user')

	def get_message_history(self):
		return self.message_history


class Alice(Chatbot):
	"""  A basic chatbot

	"""

	def _create_response(self):
		return 'Hello, My name is Alice!'


class ChatbotFactory(object):
	""" Used to produce instances of the "Chatbot" class.

	Examples:
		>>> botFactory = ChatbotFactory()
		>>> alice = botFactory.create_chatbot(name='alice')
		>>> default_bot = botFactory.create_chatbot()

	"""

	chatbot_repo = {'alice': Alice}

	def __init__(self):
		pass

	def create_chatbot(self, **kwargs):
		if 'name' in kwargs:
			requested_chatbot = kwargs['name']
			if requested_chatbot in self.chatbot_repo:
				return self.chatbot_repo[requested_chatbot]()
		else:
			return Chatbot()

class ChatbotTest(unittest.TestCase):

	def setUp(self):
		self.botFactory = ChatbotFactory()	
		pass

	def alice_test(self):

		alice = self.botFactory.create_chatbot(name='alice')

		alice.recieve('Hello, Alice!')
		print alice.respond()

		print alice.get_message_history()

	def default_chabot_test(self):

		chatbot = self.botFactory.create_chatbot()

def dialogue_test():
	msg = "not empty"
	chatbot = Chatbot()

	while msg:
		msg = raw_input(">>> ")
		chatbot.recieve(msg)
		output = chatbot.respond()
		print output

if __name__ == '__main__':
	#unittest.main()
	dialogue_test()
